name: CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t barthsuperexpansao/se-admin-react .
      - name: Publish image to docker hub
        run: docker push barthsuperexpansao/se-admin-react:latest
  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        run: docker pull barthsuperexpansao/se-admin-react:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 80:80 -p 443:443 \
          -v /etc/letsencrypt/live/admin.teste.com/fullchain.pem:/etc/nginx/certs/fullchain.pem \
          -v /etc/letsencrypt/live/admin.teste.com/privkey.pem:/etc/nginx/certs/privkey.pem \
          --name reactContainer barthsuperexpansao/se-admin-react
